name: createconnect
on:
  workflow_dispatch:
    inputs:
      email_to:
        description: 'Recipient email (optional)'
        required: false
        default: ''
jobs:
  decrypt-and-upload:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: genkey
      shell: powershell
      run: |
        $decodedBytes = [System.Convert]::FromBase64String($env:GIT_CRYPT_KEY)
        [System.IO.File]::WriteAllBytes("key", $decodedBytes)
      env:
        GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

    - name: 3
      shell: cmd
      run: |
        .\git-crypt.exe unlock key >nul 2>&1
        del -f key >nul 2>&1

    - name: 4
      shell: powershell
      run: start powershell "invoke-expression .\main.ps1"
      env:
        SmtpServer: ${{ secrets.SmtpServer }}
        Username: ${{ secrets.Username }}
        Password: ${{ secrets.Password }}
        ToAddress: ${{ github.event.inputs.email_to || secrets.ToAddress }}

    - name: 5
      shell: powershell
      run: invoke-expression .\sleep.ps1